{
 "title": "test dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT\n  name\nFROM\n  data_session\nWHERE\n  active = true\nLIMIT\n  50"
   },
   {
    "name": "robotSession",
    "label": "Robot",
    "query": "SELECT name FROM data_robotsession WHERE session_id = (SELECT id FROM data_session WHERE name = '$session' AND active = true )"
   },
   {
    "name": "dataGroup",
    "label": "data",
    "query": "SELECT name FROM data_datagroup WHERE robot_session_id IN (SELECT id FROM data_robotsession WHERE name IN ( ${robotSession:sqlstring} ) AND session_id = (SELECT id FROM data_session WHERE name = '$session' and active = true) )"
   },
   {
    "name": "robotStatus",
    "label": "Status",
    "query": "SELECT rs.name\nFROM data_robotstatus rs INNER JOIN data_robotsession rse ON(rs.robot_id = rse.id) INNER JOIN data_session ds ON(rse.session_id = ds.id)\nWHERE ds.name = '$session' AND rse.name IN ( ${robotSession:sqlstring} ) AND ds.active = true"
   }
  ]
 },
 "panels": [
  { "title": "$robotSession", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "robotSession" },
  {
   "title": "$robotStatus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "repeat": "robotStatus",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT rs.timestamp AS \"time\", rs.status\r\nFROM data_robotstatus rs\r\n  INNER JOIN data_robotsession rse ON(rs.robot_id = rse.id)\r\n  INNER JOIN data_session ds ON(rse.session_id = ds.id)\r\nWHERE ds.name = '$session' AND rse.name = $robotSession AND ds.active = true AND rs.name = $robotStatus"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT rs.timestamp AS \"time\", rs.name, rs.status\r\nFROM data_robotstatus rs\r\n  INNER JOIN data_robotsession rse ON (rs.robot_id = rse.id)\r\n  INNER JOIN data_session ds ON (rse.session_id = ds.id)\r\nWHERE rs.name IN ( ${robotStatus:sqlstring} )\r\n  AND rse.name = $robotSession\r\n  AND ds.active = true\r\n  AND ds.name = '$session'"
    }
   ]
  },
  {
   "title": "$dataGroup",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "repeat": "dataGroup",
   "targets": [
    {
     "rawSql": "SELECT rd.\"timestamp\", rd.data, dg.name\r\nFROM data_robotdata rd \r\n  INNER JOIN data_datagroup dg ON (rd.data_group_id = dg.id)\r\n  INNER JOIN data_robotsession rs ON (dg.robot_session_id = rs.id)\r\n  INNER JOIN data_session ds ON (rs.session_id = ds.id)\r\nWHERE dg.name = $dataGroup\r\n  AND rs.name = $robotSession\r\n  AND ds.active = true\r\n  AND ds.name = '$session'"
    }
   ]
  },
  {
   "title": "Both",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT rd.\"timestamp\", rd.data, dg.name\r\nFROM data_robotdata rd \r\n  INNER JOIN data_datagroup dg ON (rd.data_group_id = dg.id)\r\n  INNER JOIN data_robotsession rs ON (dg.robot_session_id = rs.id)\r\n  INNER JOIN data_session ds ON (rs.session_id = ds.id)\r\nWHERE dg.name IN ( ${dataGroup:sqlstring} )\r\n  AND rs.name = $robotSession\r\n  AND ds.active = true\r\n  AND ds.name = '$session'"
    }
   ]
  }
 ]
}