version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    # ports:
    #   - "8000:8000"
    volumes:
      - ./robot_ui:/code/robot_ui
      - static-volume:/code/static
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./database_data:/var/lib/postgresql/data/
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD?err}
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    restart: unless-stopped

  ros:
    build: ./ros2_ws
    volumes:
      - ./ros2_ws:/ros2_ws

  grafana:
    image: grafana/grafana-oss:10.0.2
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - db
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static-volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - web

volumes:
  static-volume:
