CREATE DATABASE robot_ui WITH ENCODING 'UTF8';
CREATE ROLE robot_ui WITH PASSWORD 'CHANGEME';
ALTER ROLE robot_ui WITH LOGIN;
ALTER ROLE robot_ui
SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE robot_ui TO robot_ui;