# Generated by Django 4.2.1 on 2023-06-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status', models.TextField()),
                ('data_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_status', to='data.datagroup')),
            ],
        ),
        migrations.CreateModel(
            name='RobotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='data.session')),
            ],
        ),
        migrations.CreateModel(
            name='RobotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.FloatField()),
                ('data_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_data', to='data.datagroup')),
            ],
        ),
        migrations.AddField(
            model_name='datagroup',
            name='robot_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_groups', to='data.robotsession'),
        ),
    ]
