# Generated by Django 4.2.1 on 2023-08-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_robotwebcam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robotsession',
            options={'default_permissions': (), 'verbose_name': 'Robot', 'verbose_name_plural': 'Robots'},
        ),
    ]
